#!/usr/bin/env python3
"""从项目根目录运行：python 问题一_求解.py

顺序：读取核验 -> 信号处理 -> 参数计算 -> 训练内筛选 -> 检验 -> 绘图 -> 导出。
默认只执行问题一。--smoke 为 P1 真实小样本链，--output-root 用于隔离复现。
"""
from __future__ import annotations
import argparse
import os
from pathlib import Path
import time

import numpy as np
import pandas as pd

from utils.q1_model import (
    FEATURES, FEATURE_ZH, FEATURE_BLOCKS, LABELS, read_inventory, load_record,
    prepare_record, window_features, file_medians, choose_variant, stable_selection,
    fit_window_scaler, apply_scaler, file_descriptors, run_sensitivity,
    filter_diagnostics, window_admission, sha256, write_json, save_csv,
)
from utils.repro_manifest import build_manifest

ROOT = Path(__file__).resolve().parent
# 把图形缓存放进本项目临时目录；不依赖系统目录写权限。
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".analysis-work/matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(ROOT / ".analysis-work/font-cache"))


def validate_exports(raw, scaled, descriptors, metadata, scaler, selected):
    """对实际导出数据作约束核验，异常直接终止。"""
    if raw[["file_id", "window_index"]].duplicated().any():
        raise ValueError("重复窗口键")
    if set(raw.file_id) != set(metadata.file_id) or set(descriptors.file_id) != set(metadata.file_id):
        raise ValueError("有选中文件未进入数据出口")
    if not np.isfinite(raw[FEATURES].to_numpy()).all():
        raise ValueError("原始特征有非有限值")
    if not np.isfinite(scaled[selected].to_numpy()).all():
        raise ValueError("标准化特征有非有限值")
    target = scaled[scaled.domain.eq("target")]
    if not target.label.eq("").all() or not target.label_code.eq(-1).all():
        raise ValueError("目标域出现未授权标签")
    train = scaled[scaled.split.eq("train")]
    means = train.groupby("file_id")[selected].mean().mean().to_numpy()
    second = train.copy()
    second[selected] = second[selected] ** 2
    moments = second.groupby("file_id")[selected].mean().mean().to_numpy()
    if np.max(abs(means)) > 1e-9 or np.max(abs(moments - 1)) > 1e-9:
        raise ValueError("文件等权训练标准化未达到零均值/单位方差")
    expected_fit = sorted(metadata[metadata.split.eq("train")].file_id)
    if scaler["fit_file_ids"] != expected_fit:
        raise ValueError("拟合文件集合不符合训练划分")
    return {"finite_features": True, "unique_window_keys": True,
            "all_selected_files_covered": True, "target_labels_unknown": True,
            "max_weighted_mean_error": float(np.max(abs(means))),
            "max_weighted_second_moment_error": float(np.max(abs(moments - 1))),
            "fit_files": len(expected_fit), "train_only_fit": True}


def prepare_output(path, overwrite):
    path = path.resolve()
    if not path.is_relative_to(ROOT):
        raise ValueError("输出必须位于本项目或 .analysis-work/ 下")
    for protected in ["数据集", "预处理数据集", "math-modeling-skill", "skills", ".git"]:
        if path.is_relative_to(ROOT / protected):
            raise ValueError(f"输出不能进入只读目录 {protected}")
    marker = path / ".q1-generated"
    if path.exists() and any(path.iterdir()) and (not overwrite or not marker.is_file()):
        raise FileExistsError(f"输出目录非空: {path}；本程序已有产物才可用 --overwrite 覆盖")
    path.mkdir(parents=True, exist_ok=True)
    marker.write_text("Generated by 问题一_求解.py; input data are read-only.\n", encoding="utf-8")


def report_text(summary, selection, scores, sensitivity, edge, mechanism=None):
    names = dict(zip(FEATURES, FEATURE_ZH))
    selected_text = "、".join(names[f] for f in summary["selected_features"])
    scores_mean = scores.groupby("variant", sort=False).score.mean()
    score_lines = "\n".join(f"| {key} | {value:.6f} |" for key, value in scores_mean.items())
    feature_lines = "\n".join(
        f"| {names[r.feature]} | {r.selection_frequency:.2f} | {r.fisher_score:.4f} | {'保留' if r.selected else '未保留'} |"
        for r in selection.itertuples())
    sensitivity_text = "小样本模式只核验主链，完整压力试验在全量运行中执行。"
    edge_text = ""
    mechanism_text = ""
    if mechanism is not None:
        lines = []
        for row in mechanism.itertuples():
            if row.label in ["OR", "IR", "B"]:
                lines.append(f"| {row.label} | {row.dominant_order_1_to_10:.2f} | "
                             f"{float(row.theoretical_order):.4f} | {float(row.absolute_difference):.4f} |")
        mechanism_text = (
            "\n\n| 代表文件类别 | 1—10阶内最大谱峰 | 题面理论基阶 | 绝对偏差（阶） |\n"
            "|---|---:|---:|---:|\n" + "\n".join(lines) +
            "\n\nOR与IR代表记录的最大峰接近题面参照，滚动体代表记录的最大峰偏差较大。"
            "这表明单个最大峰不足以作为故障部位的判别规则；本次保留原标签和综合特征，"
            "没有按理论位置强行移动谱峰。所列偏差只描述这些代表记录，不是全数据的诊断误差。")
    if not sensitivity.empty:
        table = sensitivity[sensitivity.rpm_change.ne(0)].groupby("route").common_scale_drift.agg(["median", "max"])
        sensitivity_text = "\n".join(
            f"- {route}：非零转速扰动下，统一主线尺度漂移的中位数 {r['median']:.4f}，最大值 {r['max']:.4f}。"
            for route, r in table.iterrows())
        compare = table.loc["equal_revolutions", "median"] - table.loc["one_second", "median"]
        sensitivity_text += (
            "\n\n本次等转数方案的中位漂移小于一秒基线，但这只支持该组特征的转速稳定性。"
            if compare < 0 else
            "\n\n本次等转数方案的中位漂移未低于一秒基线，因此目前没有“等转数更稳健”的证据；两种表征均保留到问题二作文件级诊断对照。")
        nonbase = edge[~np.isclose(edge.guard_seconds, summary["parameters"]["edge_guard_seconds"])]
        edge_text = "\n\n裁边25/75毫秒相对50毫秒的统一尺度漂移：\n\n" + "\n".join(
            f"- {route}：中位数 {group.common_scale_drift.median():.4f}，最大值 {group.common_scale_drift.max():.4f}。"
            for route, group in nonbase.groupby("route"))
    return f"""# 问题一实际运行结果

本报告由程序从本次输出生成。问题一完成源域筛选、代表性信号分析、整体特征提取和两种后续输入准备；诊断精度、目标预测和迁移优劣留待问题二、三实施后检验。

## 1. 输入和覆盖

- 运行模式：{"真实小样本核验" if summary["smoke"] else "全量"}。
- 本次覆盖 {summary["source_files"]} 个源文件和 {summary["target_files"]} 个目标文件。
- 主线共 {summary["main_windows"]} 个完整窗口，一秒基线 {summary["baseline_windows"]} 个完整窗口。
- 所有输入哈希匹配既有清单；文件归属继承原划分，拟合只使用 {summary["validation"]["fit_files"]} 个源训练文件。
- 10、20转均满足准入；40转在最短记录中失败。未补零、复制或删除短记录。
- 目标标签全部保留为空，数值编码为 -1；本阶段没有生成目标诊断标签。

## 2. 真实参数选择

选定频带 **{summary["chosen_band_hz"][0]}—{summary["chosen_band_hz"][1]} Hz**，等转数 **{summary["chosen_revolutions"]} 转**。
准则是训练内部二折文件级 Fisher 统计的平均对数分数，不是分类准确率，也不证明目标域效果。

| 候选方案（频带 Hz / 转数） | 两折平均分 |
|---|---:|
{score_lines}

## 3. 稳定筛选与数据出口

十二个候选量中保留 {len(summary["selected_features"])} 个：**{selected_text}**。
表中比例来自100次按类别分层的文件重采样，不是置信概率。正常类训练只有2个独立文件，重采样不能补足正常状态多样性。

| 特征 | 重采样入选比例 | 完整训练 Fisher 分数 | 最终处理 |
|---|---:|---:|---|
{feature_lines}

主线输出标准化窗口特征；最优传输对照输出 **{summary["descriptor_dimensions"]} 维文件描述量**，由同一组特征的中位数与四分位距构成，再用源训练文件拟合尺度。特征分块保存在数据字典中。原采样率幅值量仍受采样带宽和传感器增益影响，不将全部幅值差异归为故障差异。

0.5/0.6/0.7 阈值的入选集合见 selection_thresholds.json；本次使用预先确定的0.6。全部12个候选特征也已保存，便于下一问重新按内折筛选和拟合，不能把已拟合标准化表直接当作内折验证的输入。

## 4. 实现与稳定性检验

文件等权标准化的最大中心误差为 {summary["validation"]["max_weighted_mean_error"]:.3g}，最大二阶矩误差为 {summary["validation"]["max_weighted_second_moment_error"]:.3g}。
滤波器中心增益、阻带、完整窗覆盖、有限性、窗口唯一性和未知标签约束已通过程序检查。

{sensitivity_text}
{edge_text}

增益齐次性是程序实现检查，不代表模型已经适应真实设备增益。理论上前三个幅值特征随增益同比变化，其余归一化指标不变；实际误差见 gain_checks.csv，独立合成信号测试还检查重新滤波后的结果。

## 5. 图表与可解释边界

原始数据图展示独立文件数量、采样/转速条件和代表波形；过程图展示实际候选分数、解调及稳定选择；结果图以文件中位数展示分布、相关和转速漂移。所有图的样本单位和统计口径见图表清单。

同类文件代表性分析使用预先固定的首个训练文件，避免按图像效果挑记录。源域包络阶次图使用SKF6205题面几何作为参照，实测峰是否接近理论位置见 source_mechanism_checks.csv。滚动体采用题面冲击频率口径；目标图没有假定轴承几何。
{mechanism_text}

相关性低和训练内类间分离只是表征诊断；主峰来自有限阶次网格，并不等于已识别的真实故障频率。固定一秒基线与等转数主线使用相同频带和特征集合，保留各自尺度及统一尺度两种漂移值。

## 6. 本阶段交付

- 数学合同：项目根目录的 问题一_数学模型与求解说明.md，公式(1.01)—(1.36)。
- 数据：模型适配数据集/q1/，含全部候选特征、两方案标准化窗表和运输文件描述量。
- 证据：本目录中的候选评分、分折记录、尺度、敏感性、频响、复现与输出哈希。
- 图：figures/q1/ 的SVG/300DPI PNG及两张流程图。

完成问题一并提交GitHub后等待用户确认，再进入问题二。最优传输只是已备好的问题三对照接口，本阶段未求运输矩阵。
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--output-root", type=Path, help="隔离输出；内部创建 data/results/figures")
    parser.add_argument("--config", type=Path, default=ROOT / "configs/q1.json")
    parser.add_argument("--no-plots", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    import json
    config = json.loads(args.config.read_text(encoding="utf-8"))
    started = time.perf_counter()
    if args.smoke and args.output_root is None:
        parser.error("--smoke 必须指定隔离的 --output-root")
    if args.output_root:
        base = args.output_root.resolve()
        data_dir, result_dir, figure_dir = (base / key for key in ["data", "results", "figures"])
    else:
        data_dir, result_dir, figure_dir = (ROOT / "模型适配数据集/q1",
                                          ROOT / "results/q1", ROOT / "figures/q1")
    for directory in [data_dir, result_dir, figure_dir]:
        prepare_output(directory, args.overwrite)
    print("1/7 读取文件清单与原始记录，核对输入哈希", flush=True)
    inventory, metadata = read_inventory(ROOT, args.smoke)
    records = [load_record(ROOT, row) for row in metadata.to_dict("records")]
    save_csv(inventory, data_dir / "source_selection.csv")
    save_csv(metadata, data_dir / "files.csv")
    admission = window_admission(metadata, config)
    save_csv(admission, result_dir / "window_admission.csv")
    save_csv(filter_diagnostics(config), result_dir / "filter_diagnostics.csv")
    print("2/7 原采样率解调、重采样包络、构造候选窗口", flush=True)
    candidate_lists, coverage_lists, envelopes_by_band = {}, {}, {}
    specifications = {}
    for band_index, band in enumerate(config["bands_hz"]):
        envelopes_by_band[band_index] = {}
        for revolutions in config["revolutions"]:
            key = f"{band[0]}-{band[1]}Hz_R{revolutions}"
            candidate_lists[key], coverage_lists[key] = [], []
            specifications[key] = (band_index, revolutions)
    for position, record in enumerate(records):
        for band_index, band in enumerate(config["bands_hz"]):
            envelope = prepare_record(record, band, config)
            envelopes_by_band[band_index][record.file_id] = envelope
            for revolutions in config["revolutions"]:
                key = f"{band[0]}-{band[1]}Hz_R{revolutions}"
                frame, coverage = window_features(record, envelope, revolutions, config)
                candidate_lists[key].append(frame)
                coverage_lists[key].append(coverage)
        if (position + 1) % 20 == 0:
            print(f"  已处理 {position + 1}/{len(records)} 个文件", flush=True)
    candidates = {name: pd.concat(frames, ignore_index=True)
                  for name, frames in candidate_lists.items()}
    print("3/7 训练文件内计算参数分数与特征稳定性", flush=True)
    winner, scores, folds = choose_variant(candidates, metadata, config)
    band_index, revolutions = specifications[winner]
    band, envelopes = config["bands_hz"][band_index], envelopes_by_band[band_index]
    main_frame = candidates[winner]
    selected, selection, thresholds = stable_selection(main_frame, metadata, config)
    save_csv(scores, result_dir / "candidate_scores.csv")
    save_csv(folds.rename_axis("file_id").reset_index(), result_dir / "training_inner_folds.csv")
    save_csv(selection, result_dir / "feature_selection.csv")
    write_json(result_dir / "selection_thresholds.json", thresholds)
    training_ids = metadata[metadata.split.eq("train")].file_id
    all_candidate_medians = pd.concat([
        file_medians(frame).loc[training_ids].assign(variant=name).reset_index()
        for name, frame in candidates.items()], ignore_index=True)
    save_csv(all_candidate_medians, result_dir / "candidate_training_file_medians.csv")
    baseline_parts, baseline_coverage = [], []
    for record in records:
        frame, coverage = window_features(record, envelopes[record.file_id], None, config)
        baseline_parts.append(frame)
        baseline_coverage.append(coverage)
    baseline_frame = pd.concat(baseline_parts, ignore_index=True)
    print("4/7 冻结特征与训练尺度，生成窗口/文件两种接口", flush=True)
    main_scaler = fit_window_scaler(main_frame, selected)
    baseline_scaler = fit_window_scaler(baseline_frame, selected)
    main_scaled = apply_scaler(main_frame, main_scaler)
    baseline_scaled = apply_scaler(baseline_frame, baseline_scaler)
    desc_raw, desc_scaled, descriptor_scaler = file_descriptors(main_scaled, selected, config)
    validation = validate_exports(main_frame, main_scaled, desc_scaled, metadata, main_scaler, selected)
    validate_exports(baseline_frame, baseline_scaled, desc_scaled, metadata, baseline_scaler, selected)
    for filename, frame in [
        ("window_features_all.csv", main_frame), ("window_features_selected_scaled.csv", main_scaled),
        ("baseline_1s_features_all.csv", baseline_frame),
        ("baseline_1s_selected_scaled.csv", baseline_scaled),
        ("uot_file_descriptors_unscaled.csv", desc_raw),
        ("uot_file_descriptors_scaled.csv", desc_scaled),
        ("window_coverage.csv", pd.DataFrame(coverage_lists[winner])),
        ("baseline_1s_coverage.csv", pd.DataFrame(baseline_coverage)),
    ]:
        save_csv(frame, data_dir / filename)
    for filename, value in [
        ("window_scaler.json", main_scaler), ("baseline_window_scaler.json", baseline_scaler),
        ("file_descriptor_scaler.json", descriptor_scaler),
    ]:
        write_json(result_dir / filename, value)
    dictionary = [{"feature": feature, "chinese": name, "equation": f"1.{index + 12:02}",
                   "block": FEATURE_BLOCKS[feature], "selected": feature in selected,
                   "unit": "unknown_original_scale" if index < 3 else "dimensionless"}
                  for index, (feature, name) in enumerate(zip(FEATURES, FEATURE_ZH))]
    write_json(data_dir / "feature_dictionary.json", dictionary)
    print("5/7 结果约束与敏感性检验", flush=True)
    sensitivity = edge = gain = pd.DataFrame()
    if not args.smoke:
        sensitivity, edge, gain = run_sensitivity(
            records, envelopes, revolutions, selected, config, main_scaler,
            baseline_scaler, main_frame, baseline_frame)
        save_csv(sensitivity, result_dir / "rpm_sensitivity.csv")
        save_csv(edge, result_dir / "edge_sensitivity.csv")
        save_csv(gain, result_dir / "gain_checks.csv")
    summary = {
        "smoke": args.smoke, "source_files": int(metadata.domain.eq("source").sum()),
        "target_files": int(metadata.domain.eq("target").sum()),
        "main_windows": len(main_frame), "baseline_windows": len(baseline_frame),
        "chosen_variant": winner, "chosen_band_hz": band, "chosen_revolutions": revolutions,
        "selected_features": selected, "descriptor_dimensions": len(descriptor_scaler["features"]),
        "validation": validation, "parameters": config,
    }
    write_json(result_dir / "summary.json", summary)
    from utils.profile_data import profile_data, render_report
    profile_frame = metadata[["file_id", "domain", "label", "split"]].merge(
        file_medians(main_frame).reset_index(), on="file_id")
    profile = profile_data(profile_frame, group_cols=["domain", "label"])
    write_json(result_dir / "feature_profile.json", profile)
    (result_dir / "feature_profile.md").write_text(render_report(profile), encoding="utf-8")
    print("6/7 绘图（小样本核验模式不生成正式图）", flush=True)
    if not args.smoke and not args.no_plots:
        from utils.q1_plots import make_figures
        make_figures(records, metadata, main_frame, main_scaled, selection, scores,
                     sensitivity, band, revolutions, envelopes, selected, config,
                     figure_dir, result_dir)
    print("7/7 导出实际结果、运行清单和哈希", flush=True)
    mechanism = (pd.read_csv(result_dir / "source_mechanism_checks.csv", keep_default_na=False)
                 if not args.smoke and not args.no_plots else None)
    (result_dir / "问题一_结果报告.md").write_text(
        report_text(summary, selection, scores, sensitivity, edge, mechanism), encoding="utf-8")
    inputs = [ROOT / "数据集" / p for p in metadata.relative_path]
    inputs += [ROOT / "预处理数据集/files.csv", args.config.resolve(),
               ROOT / "问题一_数学模型与求解说明.md", ROOT / "问题一_求解.py",
               ROOT / "requirements-q1.txt", *sorted((ROOT / "utils").glob("*.py"))]
    command = "python 问题一_求解.py"
    if args.smoke:
        command += " --smoke"
    if args.output_root:
        command += f' --output-root "{args.output_root}"'
    if args.no_plots:
        command += " --no-plots"
    if args.config.resolve() != ROOT / "configs/q1.json":
        command += f' --config "{args.config}"'
    command += " --overwrite"
    manifest = build_manifest(inputs, config["seed"], config, command,
                              ["numpy", "scipy", "pandas", "matplotlib", "pillow"])
    for entry in manifest["input_files"]:
        entry["path"] = str(Path(entry["path"]).relative_to(ROOT))
    manifest["duration_seconds"] = time.perf_counter() - started
    manifest["stage"] = "Q1_only"
    manifest["chosen_variant"] = winner
    manifest["outputs"] = []
    for directory in [data_dir, result_dir, figure_dir]:
        for path in sorted(directory.rglob("*")):
            if path.is_file() and path.name not in [".q1-generated", "复现清单.json", "README.md"]:
                manifest["outputs"].append({"path": str(path.relative_to(ROOT)),
                                            "sha256": sha256(path), "bytes": path.stat().st_size})
    write_json(result_dir / "复现清单.json", manifest)
    print(f"完成问题一: {winner}; {len(selected)} 个特征; {len(main_frame)} 个窗口; "
          f"{manifest['duration_seconds']:.1f} 秒", flush=True)


if __name__ == "__main__":
    main()
