#!/usr/bin/env python3
"""问题三：读取 Q1 特征、代理选择、迁移诊断、稳定性和结果导出。

从项目根目录运行。`--smoke` 只验证真实数据的最小纵向链；完整运行在 P1 后执行。
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import time

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

from utils.q1_model import load_record, prepare_record, save_csv, window_features, write_json
from utils.q3_transfer import (
    CLASS_ORDER, file_median_table, fit_transfer, predict_frame, proxy_metrics,
    select_alpha,
)
from utils.q3_outputs import (alignment_diagnostics, export_transfer_model,
                              write_result_report)


ROOT = Path(__file__).resolve().parent


def prepare_output(path: Path, overwrite: bool) -> None:
    path = path.resolve()
    if not path.is_relative_to(ROOT):
        raise ValueError("输出目录必须在项目内")
    for protected in ["数据集", "预处理数据集", "math-modeling-skill", "skills", ".git"]:
        if path.is_relative_to(ROOT / protected):
            raise ValueError("输出目录不能位于输入或技能目录")
    marker = path / ".q3-generated"
    if path.exists() and any(path.iterdir()) and (not overwrite or not marker.exists()):
        raise FileExistsError("非本程序生成的非空目录不可覆盖")
    path.mkdir(parents=True, exist_ok=True)
    marker.write_text("Generated by 问题三_求解.py; source inputs remain read-only.\n",
                      encoding="utf-8")


def read_inputs(config: dict) -> tuple[pd.DataFrame, pd.DataFrame]:
    metadata = pd.read_csv(ROOT / "模型适配数据集/q1/files.csv", keep_default_na=False)
    windows = pd.read_csv(ROOT / "模型适配数据集/q1/window_features_all.csv",
                          keep_default_na=False)
    if len(metadata) != 132 or len(windows) != 996:
        raise ValueError("Q1 固定输入规模变化，请重新核对表征")
    if metadata.file_id.duplicated().any() or len(set(config["features"])) != 9:
        raise ValueError("文件键或迁移特征合同变化")
    if not metadata[metadata.domain.eq("target")].label.eq("").all():
        raise ValueError("目标域标签必须未知")
    if not metadata[metadata.domain.eq("target")].label_code.eq(-1).all():
        raise ValueError("目标域数值标签必须为-1")
    files = file_median_table(windows, metadata, config["features"])
    counts = files[files.domain.eq("source")].split.value_counts()
    if [int(counts.get(x, 0)) for x in ["train", "validation", "test"]] != [70, 23, 23]:
        raise ValueError("源域固定划分不是70/23/23")
    if files[files.domain.eq("target")].n_windows.ne(3).any():
        raise ValueError("目标20转窗口覆盖变化")
    return files, metadata


def source_metrics(frame: pd.DataFrame) -> dict:
    truth, predicted = frame.true_label, frame.prediction
    return {"files": len(frame), "correct": int((truth == predicted).sum()),
            "accuracy": float(accuracy_score(truth, predicted)),
            "balanced_accuracy": float(balanced_accuracy_score(truth, predicted)),
            "macro_f1": float(f1_score(truth, predicted, labels=CLASS_ORDER,
                                       average="macro", zero_division=0))}


def recalculate_target_at_rpm(metadata: pd.DataFrame, q1: dict, rpm: int,
                              features: list[str]) -> pd.DataFrame:
    band = q1["chosen_band_hz"]
    parameters = q1["parameters"]
    frames = []
    for row in metadata[metadata.domain.eq("target")].sort_values("file_id").to_dict("records"):
        record = load_record(ROOT, row)
        envelope = prepare_record(record, band, parameters)
        window_table, _ = window_features(
            record, envelope, q1["chosen_revolutions"], parameters,
            rpm_change=rpm / float(row["rpm"]) - 1,
        )
        frames.append(window_table)
    recomputed = pd.concat(frames, ignore_index=True)
    return file_median_table(recomputed, metadata[metadata.domain.eq("target")], features)


def target_sensitivity(dev: pd.DataFrame, target: pd.DataFrame, metadata: pd.DataFrame,
                       q1: dict, config: dict, alpha: float,
                       baseline: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    # 留一时每次用其余15文件重估无标签统计量，源域重新映射并重训。
    loo_rows = []
    for held in target.itertuples(index=False):
        target_fit = target[target.file_id.ne(held.file_id)]
        held_frame = target[target.file_id.eq(held.file_id)]
        scale, _, model = fit_transfer(dev, target_fit, config, alpha, CLASS_ORDER)
        predicted = predict_frame(model, scale.transform(held_frame), held_frame,
                                  CLASS_ORDER).prediction.iloc[0]
        loo_rows.append({"file_id": held.file_id, "loo_prediction": predicted})
    loo = pd.DataFrame(loo_rows)

    # 600 rpm 基准已由 Q1 表生成，另外两个题面近似转速从原MAT完整重算。
    speed_rows = []
    for rpm in [540, 660]:
        altered_target = recalculate_target_at_rpm(metadata, q1, rpm, config["features"])
        scale, _, model = fit_transfer(dev, altered_target, config, alpha, CLASS_ORDER)
        frame = predict_frame(model, scale.transform(altered_target), altered_target,
                              CLASS_ORDER)
        for item in frame.itertuples(index=False):
            speed_rows.append({"file_id": item.file_id, "rpm_assumed": rpm,
                               "prediction": item.prediction, "margin": item.margin})
    speed = pd.DataFrame(speed_rows)
    base_labels = baseline.set_index("file_id").prediction
    for item in loo.itertuples(index=False):
        if item.file_id not in base_labels:
            raise ValueError("留一文件不在基准预测中")
    return loo, speed


def main() -> None:
    parser = argparse.ArgumentParser(description="问题三无标签迁移诊断")
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--output-root", type=Path, default=Path("results/q3"))
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    started = time.perf_counter()
    output = (ROOT / args.output_root).resolve()
    prepare_output(output, args.overwrite)
    config = json.loads((ROOT / "configs/q3.json").read_text(encoding="utf-8"))
    q1 = json.loads((ROOT / "results/q1/summary.json").read_text(encoding="utf-8"))
    files, metadata = read_inputs(config)
    source = files[files.domain.eq("source")]
    target = files[files.domain.eq("target")]

    if args.smoke:
        training = source[source.split.eq("train")]
        sampled = pd.concat([training[training.label.eq(label)].head(2)
                             for label in CLASS_ORDER], ignore_index=True)
        held = target.head(4)
        scale, alignment, model = fit_transfer(sampled, held, config, .25, CLASS_ORDER)
        predicted = predict_frame(model, scale.transform(held), held, CLASS_ORDER)
        save_csv(predicted, output / "smoke_target_predictions.csv")
        write_json(output / "summary.json", {
            "mode": "smoke", "fit_files": len(sampled), "target_files": len(held),
            "n_features": len(config["features"]), "alpha": alignment.alpha,
            "finite_scores": bool(np.isfinite(predicted[[f"score_{c}" for c in CLASS_ORDER]]
                                                .to_numpy()).all()),
            "elapsed_seconds": time.perf_counter() - started,
        })
        print(f"smoke: {len(sampled)} source fit, {len(held)} target, 9 features")
        return

    # 全量计算仅在 P1 通过后调用。
    development = source[source.split.isin(["train", "validation"])].copy()
    test = source[source.split.eq("test")].copy()
    proxy = proxy_metrics(development, config)
    alpha = select_alpha(proxy)
    save_csv(proxy, output / "proxy_metrics.csv")
    save_csv(files, output / "file_medians_nine_features.csv")

    base_scale, _, base_model = fit_transfer(development, target, config, 0.0, CLASS_ORDER)
    scale, alignment, model = fit_transfer(development, target, config, alpha, CLASS_ORDER)
    diagnostics = alignment_diagnostics(scale.transform(development),
                                        scale.transform(target), alignment)
    save_csv(diagnostics, output / "alignment_diagnostics.csv")
    export_transfer_model(output, config, q1, scale, alignment, model,
                          scale.transform(target))
    source_base = predict_frame(base_model, base_scale.transform(test), test, CLASS_ORDER)
    source_base.insert(0, "model", "source_no_alignment")
    source_aligned = predict_frame(model, alignment.transform_source(scale.transform(test)),
                                   test, CLASS_ORDER)
    source_aligned.insert(0, "model", "target_aligned")
    source_predictions = pd.concat([source_base, source_aligned], ignore_index=True)
    save_csv(source_predictions, output / "source_test_predictions.csv")

    target_base = predict_frame(base_model, base_scale.transform(target), target,
                                CLASS_ORDER)
    target_final = predict_frame(model, scale.transform(target), target, CLASS_ORDER)
    loo, speed = target_sensitivity(development, target, metadata, q1, config, alpha,
                                    target_final)
    speed_wide = speed.pivot(index="file_id", columns="rpm_assumed", values="prediction")
    speed_wide.columns = [f"rpm_{rpm}_prediction" for rpm in speed_wide.columns]
    target_output = target_final.drop(columns=["domain", "split", "true_label"])
    target_output = target_output.merge(
        target_base[["file_id", "prediction"]].rename(
            columns={"prediction": "source_baseline_prediction"}),
        on="file_id", validate="one_to_one")
    target_output = target_output.merge(loo, on="file_id", validate="one_to_one")
    target_output = target_output.merge(speed_wide.reset_index(), on="file_id",
                                        validate="one_to_one")
    target_output["branch_agreement"] = target_output.prediction.eq(
        target_output.source_baseline_prediction)
    target_output["loo_agreement"] = target_output.prediction.eq(
        target_output.loo_prediction)
    target_output["rpm_agreement_fraction"] = (
        target_output.prediction.eq(target_output.rpm_540_prediction).astype(float)
        + target_output.prediction.eq(target_output.rpm_660_prediction).astype(float)) / 2
    target_output["review_flag"] = (~target_output.branch_agreement
                                    | ~target_output.loo_agreement
                                    | target_output.rpm_agreement_fraction.lt(1))
    save_csv(target_output, output / "target_file_labels.csv")
    save_csv(speed, output / "rpm_sensitivity_predictions.csv")
    save_csv(loo, output / "target_leave_one_out.csv")

    summary = {
        "mode": "full", "source_files": len(source), "source_development": len(development),
        "source_test": len(test), "target_files": len(target), "target_truth_available": False,
        "target_accuracy": None, "n_features": len(config["features"]),
        "target_window_count": int(files[files.domain.eq("target")].n_windows.sum()),
        "alpha_selected": alpha, "proxy_selection": "lexicographic_min_mean_negative_alpha",
        "source_baseline_metrics": source_metrics(source_base),
        "source_aligned_metrics": source_metrics(source_aligned),
        "target_predicted_counts": target_output.prediction.value_counts().to_dict(),
        "target_branch_agreement": float(target_output.branch_agreement.mean()),
        "target_loo_agreement": float(target_output.loo_agreement.mean()),
        "target_rpm_full_agreement": float(target_output.rpm_agreement_fraction.eq(1).mean()),
        "target_review_files": int(target_output.review_flag.sum()),
        "scale_zero_iqr": list(scale.zero_iqr),
        "block_shrinkage": {name: {"source": block.source_shrinkage,
                                   "target": block.target_shrinkage}
                            for name, block in alignment.blocks.items()},
        "elapsed_seconds": time.perf_counter() - started,
    }
    write_json(output / "summary.json", summary)
    write_result_report(output, summary, proxy, target_output, diagnostics)
    from utils.q3_plots import make_q3_figures
    make_q3_figures(ROOT / "figures/q3", output, files, proxy, diagnostics,
                    target_output, summary)
    from utils.q3_manifest import write_q3_manifest
    write_q3_manifest(output, config, summary)
    print(json.dumps({"alpha": alpha, "source_test_correct":
                      summary["source_aligned_metrics"]["correct"],
                      "target_predicted_counts": summary["target_predicted_counts"],
                      "target_review_files": summary["target_review_files"]},
                     ensure_ascii=False))


if __name__ == "__main__":
    main()
